### ISSUE TITLE
[iOS] bug with @react-navigation/bottom-tabs

### ISSUE THREAD

**Issue by Hirbod** [software-mansion/react-native-screens#1251]
## Description

When using @react-navigation/bottom-tabs with RNS, the content jumps on tab change (one the first render only).
I made sure I've tested this plenty of times. 

The bug does not occur if I import 
```tsx
import { createStackNavigator } from '@react-navigation/stack';
```

but with

```tsx
import { createNativeStackNavigator } from '@react-navigation/native-stack';
```

My whole is wrapped with `SafeAreaProvider` from `react-native-safe-area-context` like so:
```tsx
import {
  SafeAreaProvider,
  initialWindowMetrics
} from 'react-native-safe-area-context';
```

```tsx
        <SafeAreaProvider initialMetrics={initialWindowMetrics}>
            <Navigator theme={combinedTheme} />
        </SafeAreaProvider>
```

I also tried to test it without initialMetrics and also used `SafeAreaView`(from react-native-safe-area-context and react-native), but it still jumped for me.

I also patched react-navigation bottoms tabs with this PR applied by @WoLewicki
https://github.com/react-navigation/react-navigation/pull/9772

But the jump still occur. Also made sure to disable/enable freeze etc. 
I couldn't manage to prevent the initial jumping. See my video attached.

## Steps To Reproduce

I created a dead simple preview, see my Video below. Please watch the in the center.
https://streamable.com/i7upqv

### Expected behavior
Should not jump on initial render

### Actual behavior
It jumps on initial render and it does look weird

## Reproduction
Happens on iOS, snack not helping here.

## Platform

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [X] Managed workflow
- [X] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |  0.64.3       |
| @react-navigation/native               |  6.0.6       |
| @react-navigation/native-stack         |    6.2.5     |
| react-native-screens                   |  3.10.1       |
| react-native-safe-area-context         |  3.3.2       |
| react-native-gesture-handler           |     2.1.0    |
| react-native-reanimated                | 2.3.1        |
| expo                                   |  44.0.3       |

```log
  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 11.6.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.2 - /usr/local/opt/node@14/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/opt/node@14/bin/npm
      Watchman: 2021.12.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      react-dom: 17.0.2 => 17.0.2 
      react-native-web: 0.17.5 => 0.17.5 
    npmGlobalPackages:
      eas-cli: 0.41.1
      expo-cli: 5.0.3
    Expo Workflow: bare
```

**Comment by Hirbod** [comment]
P.S: I thought this is the right repo to post this issue. If you feel I have to post this at react-navigation, let me know.

**Comment by WoLewicki** [comment]
Can you post this simple repo with the changed applied with e.g. `patch-package` so we can work on it?

**Comment by Hirbod** [comment]
@WoLewicki I got rid of it with headerTransparent:true + remove of initialMetrics and some refactoring of my navigators, but I still think that this is bug, because it does not work with all combinations.

**Comment by WoLewicki** [comment]
Hmm if you think this is a bug on `react-native-screens` side, please provide a reproduction so we can work on it.

**Comment by Hirbod** [comment]
@WoLewicki I will provide a reproduction soon. I think it is indeed a bug on rns.

**Comment by owinter86** [comment]
A nice way this can be fixed is to wrap each screen, or at least each initial route of each tab in its own SafeAreaProvider, and the additional benefit is that any child SafeAreaView will ignore any insets that have already been applied in any parent View/Navigator, so you will never have to define the edges manually.

This was problematic on Android previously see issue https://github.com/software-mansion/react-native-screens/issues/1174, however I have just retested and no longer have this issue. I can also confirm that this method also stops the tabs from jumping on initial mount.

**Comment by pt7892** [comment]
@WoLewicki 

Here is repo with reproduced bug: https://github.com/pt7892/rnscreens-bottom-tab-flicker

also videos: 


https://user-images.githubusercontent.com/20343932/151573753-31677bc2-078f-4697-8fe5-ed64f1f3e1aa.mp4

https://user-images.githubusercontent.com/20343932/151573647-f13466e2-cbf4-4080-bb08-7355ca1c4255.mov

If initial tab screen is simple, you may not notice this, thats why i added bunch of `Text` and `Button` components

From what i understand, on tab change, if stack is being mounted first time, 2 `RNScreen` are being layout on screen, but not in same "tick", and thats why you may notice this flash effect

**Comment by WoLewicki** [comment]
@pt7892 is the jumping behavior connected to the flicker issue you posted here?

**Comment by pt7892** [comment]
@WoLewicki 

Actually, i was referring to this issue GH-1276, but mistakenly added comment on this one.

I see now that reproduction repo is already uploaded in GH-1276, so this [comment](https://github.com/software-mansion/react-native-screens/issues/1251#issuecomment-1024329330) can be deleted.

Sorry for the mistake

**Comment by vladyslavNiemtsev** [comment]
@hirbod  Do you have a workaround for it?

**Comment by WoLewicki** [comment]
@vladyslavNiemtsev please provide a reproduction of this issue then so we can work on it, otherwise we cannot do much about it.

**Comment by hirbod** [comment]
He is indeed right. The header is jumping on android. Only headerTransparent was helping for me

**Comment by hukpavlo** [comment]
Just a small point here, if you have headerShown: false in your BottomTabNavigator when you enable it - jumping disappears

**Comment by hirbod** [comment]
@WoLewicki this is still a thing.
The issue comes from where you add headerShown or headerTranslucent.

If you use the header provided by BottomTab, there is no jumping. But when you have a nested stack as a tab, you don't want to use the header from the BottomTab, instead you wan't to use the header provided by the nested stack.

This jumping is still super annoying and there is no real way around it. It just looks like the insets where applied too late and thats what cause the drops. There are repos available in the issue tracker, there is even a duplicated issue:
https://github.com/software-mansion/react-native-screens/issues/1276

Would be awesome if we could resolve this.

**Comment by l0gicgate** [comment]
I’m experiencing the same issue. It seems to be related to the `headerShown` option. It only happens on first render as well. 

With `headerShown: false`:
https://user-images.githubusercontent.com/6510935/173461630-7ddb650d-5ee6-41c0-80de-fa1b8a8fea0d.MOV

With `headerShown: true`:
https://user-images.githubusercontent.com/6510935/173461690-78c17f4b-0481-44c2-a100-dc724a1eabe2.MOV

What could be a potential fix for this? I need to get this resolved asap. 

Is there a version that can be reverted to where this doesn’t occur?

**Comment by pjc0247** [comment]
`useSafeAreaInsets` works for me

**Comment by sjransom** [comment]
Fixed this by swapping `<SafeAreaView />` with `useSafeAreaInsets()`

`<View style={[styles.container, { paddingTop: Math.max(insets.top, SPACING.s16) }]} {...otherProps}>`

**Comment by l0gicgate** [comment]
@sjransom see [my comment here](https://github.com/software-mansion/react-native-screens/issues/1251#issuecomment-1154533585)

You cannot use `SafeAreaView`, you have to create a regular `View` component and use the `useSafeAreaInsets()` to pad it appropriately.

**Comment by aymather** [comment]
I've tried using the custom `View` with `useSafeAreaInsets()` and I've also tried not using any `SafeAreaView` at all, and I'm still getting the glitching effect :(

**Comment by l0gicgate** [comment]
@aymather please show the smallest reproducible example possible

**Comment by aymather** [comment]
@l0gicgate Ok so I've tried reproducing the problem... and of course... no dice... but I have recreated a very basic environment to demonstrate a working concept if anyone wants to view it / try to reproduce the problem from there. [Here](https://github.com/aymather/reactNativeScreensGlitchTesting) is the repository.

I did, however, fix the problem in my app by upgrading `react-native-screens` from `3.12.0` -> `3.3.0`.

Now... I thought that the version might have something to do with the problem, so when I first tried to reproduce the problem, the version that came in when i added `react-native-screens` was `3.15.0` and the issue wasn't there. So I thought, oh ok.. this is problem something that was patched. So I then downgraded from `3.15.0` -> `3.12.0` to try to reproduce the problem. However, even after downgrading, I still was unable to get the glitch to happen...

For anyone who is still facing this issue, I'd say try removing the package from your project completely, and reinstalling it. Try the `3.3.0` version and see if that works too. Maybe a good-ole-fashioned `rm -rf node_modules && rm yarn.json && yarn` is all that's needed..? 🤷🏻‍♂️

**Comment by Rebsos** [comment]
Any update on this?
Can we have something like "headerTopInsetEnabled" from React Navigation V5 back?

**Comment by brandon-austin-lark** [comment]
I'm currently experiencing this issue. Tried all of the solutions above and no luck.

**Comment by Sumit2202** [comment]
Any update on the above issue?

**Comment by anhquan291** [comment]
Facing the same issue!

**Comment by elmaxe** [comment]
Faced the same issue today

**Comment by kickbk** [comment]
This is still an issue, frustrating. Here's a sneaky workaround that I just used, and it seems to work nicely.

I haven't dug in to see what the real cause is, but what I can tell is that both the header and bottom tab bar cause this behavior. This means that regardless of which you have displaying, it will mess things up.

What helped was "yanking out" both components so their height calculation doesn't affect the other components.

For the bottom tab bar, I make its position absolute:
```ts
<Tabs
  screenOptions={{
    ...
    tabBarStyle: {position: 'absolute'}
  }}
>
```
Then for any Stacks it contains, I make the header transparent, which removes its container height so screen components can appear behind it.

Finally, I apply bottom and top margins to the content via contentStyle to compensate for the height of the header and bottom tab bar I just removed:

```ts
<Stack
  screenOptions={{
    ...,
    headerTransparent: true,
    contentStyle: {
      marginBottom: [bottomInset + 47],
      marginTop:[topInset + 40]
    }
  }}
>
```

I'm using Expo Router and Unistyles, but this should work with whatever setup you have. 
So I use Unistyles insets + the default bottom tab bar height of 47 and the header which is 40.
You can probably use a hook to get those values.

I haven't had a chance to test this on Android or run any serious test, but it seems to work.
Hope it helps.
