### ISSUE TITLE
iOS: WebView won't unmount when go back

### ISSUE THREAD

**Issue by ouabing** [software-mansion/react-native-screens#161]
I use react-native-webview to play embed videos with react-navigation and react-native-screens 2.0 as navigation solution. The video continues to play when I go back to previous screen on iOS. The 1.0 version works fine but 2.0 not.

react-nativgation: 4.0.5
react-native-webview: 7.0.6
react-native-screens: 2.0.0-alpha.3

**Comment by ouabing** [comment]
Seem like fixed in 2.2.0+

**Comment by sumansarkarwd** [comment]
It's not fixed. I'm on latest version 2.4.0. The UI freezes for a second than the app crash.

**Comment by kmagiera** [comment]
Thank you @sumansarkarwd for your comment. Would you mind providing a small reproducable app that we can use to see the problem you are reporting?
