### ISSUE TITLE
[RN 0.75 new arch] 'utils/RectUtil.h' file not found

### ISSUE THREAD

**Issue by jankosecki** [software-mansion/react-native-screens#2306]
### Description

Hi team,

I've been testing upgrading RN 0.74 to 0.75-RC7 with basic stack including `react-navigation` and `react-native-screens`.
The iOS build fails for me with the following error:

```
In file included from /Users/jkosecki/repos/custom/ReactNativeUpgradeTester/node_modules/react-native-screens/ios/RNSScreen.mm:15:
/Users/jkosecki/repos/custom/ReactNativeUpgradeTester/node_modules/react-native-screens/common/cpp/react/renderer/components/rnscreens/RNSScreenComponentDescriptor.h:10:10: fatal error: 'utils/RectUtil.h' file not found
#include "utils/RectUtil.h"
```

I have applied the following patch locally (included in the reproduction repo):
```
diff --git a/node_modules/react-native-screens/RNScreens.podspec b/node_modules/react-native-screens/RNScreens.podspec
index be7cc24..14cd2e4 100644
--- a/node_modules/react-native-screens/RNScreens.podspec
+++ b/node_modules/react-native-screens/RNScreens.podspec
@@ -27,7 +27,7 @@ Pod::Spec.new do |s|
     s.subspec "common" do |ss|
       ss.source_files         = ["common/cpp/**/*.{cpp,h}", "cpp/**/*.{cpp,h}"]
       ss.header_dir           = "rnscreens"
-      ss.pod_target_xcconfig  = { "HEADER_SEARCH_PATHS" => "\"$(PODS_TARGET_SRCROOT)/common/cpp\"" }
+      ss.pod_target_xcconfig  = { "HEADER_SEARCH_PATHS" => "\"$(PODS_TARGET_SRCROOT)/common/cpp/react/renderer/components/\"" }
     end
   end
 
```
but I'm not sure if that's correct way to fix this issue.

### Steps to reproduce

1. Remove `patches/react-native-screens+3.34.0.patch`
2. Run `yarn setup && yarn ios`

### Snack or a link to a repository

https://github.com/jankosecki/react-native-upgrade-tester/tree/rn-0.75

### Screens version

3.34.0

### React Native version

0.75-RC7

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

None

### Acknowledgements

Yes

**Comment by necmettindev** [comment]
same issue

**Comment by nthtrung09it** [comment]
same issue

**Comment by rayson-intrack** [comment]
same issue

**Comment by tboba** [comment]
Hey, thanks for posting this issue!
Unfortunately, I can't reproduce this bug with the reproducer you provided. After removing patch I'm not receiving any error during the `pod install` phase, nor the compile phase.
Is this reproducer correct? I can't find any line for enabling new architecture in this repro 🤔

**Comment by tboba** [comment]
@necmettindev @nthtrung09it @rayson-intrack @0xDing could you provide a reproducer that reproduces this issue? As I said above, I didn't manage to deduce any bug from provided RN project (even after removing the patch).

**Comment by jankosecki** [comment]
@tboba 
I can reproduce the issues using provided repo. I did the following steps:
1. Delete `patches/react-native-screens+3.34.0.patch`
2. Clean up node_modules in case patch already applied
3. Run `yarn setup` (it invokes `"pod-install": "(cd ./ios ; RCT_NEW_ARCH_ENABLED=1 USE_FRAMEWORKS=static bundle exec pod install --repo-update)"` which enables new architecture)
4. Open XCode to set up development team (provided repro contains `None` team in Signing & Capabilities)
5. Run `yarn start`
6. Run `yarn ios` or trigger build from XCode (`yarn ios` causes a massive error output with different "error" lines but XCode offers a clear reason:
![image](https://github.com/user-attachments/assets/b5e8b938-9259-4294-add9-08ef30fb3542)

**Comment by matinzd** [comment]
This is also happening in 0.75.2. Seems like there is something wrong with the pod installation in 75.

**Comment by FurySwordXD** [comment]
Can reproduce on RN 0.75.2

**Comment by WoLewicki** [comment]
`#include <react/renderer/components/rnscreens/utils/RectUtil.h>` instead of `#include "utils/RectUtil.h"` seems to work in my setups.

**Comment by cjones26** [comment]
Same issue +1

**Comment by TowhidKashem** [comment]
same issue +1

**Comment by tboba** [comment]
@matinzd this patch sounds better. Thanks!

**Comment by matinzd** [comment]
Should I open a PR for that? Is that gonna break paper?

**Comment by tboba** [comment]
@matinzd Nope, it shouldn't. C++ layer is being built only on new architecture, so the old arch should work well 👍

**Comment by matinzd** [comment]
Any plans to release this change?

**Comment by cjones26** [comment]
It's been almost two months...this may hold up one of our releases and we really don't want to have to fork.  Can you please provide a timeline on when it will be published?

**Comment by jaaywags** [comment]
> #include <react/renderer/components/rnscreens/utils/RectUtil.h>

YES this worked for me too! Not ideal solution but at least we can move forward until the fix is released.

**Comment by sujathasperi2022** [comment]
This is still happening in RN 0.76.0 with "react-native-screens": "^3.34.0".
I was able to build ios after the below fix

> `#include <react/renderer/components/rnscreens/utils/RectUtil.h>` instead of `#include "utils/RectUtil.h"` seems to work in my setups.

**Comment by itsmuntadhar** [comment]
> This is still happening in RN 0.76.0 with "react-native-screens": "^3.34.0". I was able to build ios after the below fix
> 
> > `#include <react/renderer/components/rnscreens/utils/RectUtil.h>` instead of `#include "utils/RectUtil.h"` seems to work in my setups.

Only ways around it are:

1. manual fix (will have to be repeated on other machines, clones, etc)
2. patch
3. use v4 beta (not quite sure about newest v3 rc)

**Comment by Hao-yiwen** [comment]
same question.

**Comment by Degn** [comment]
still happening..

**Comment by WoLewicki** [comment]
Did you try running it on v. `3.35.0`of library @Degn @itsmuntadhar ?

**Comment by jessiemblack** [comment]
This is still an issue with RN 0.77.0

**Comment by kkafar** [comment]
Are you guys able to provide me with fresh project where this happens?

**Comment by rafaelbpa** [comment]
Still happening with version 4.7.0 released yesterday... RN 0.77.1

**Comment by hirbod** [comment]
Can agree, broke with todays 4.7.0 but was working with 4.7.0.beta.4

**Comment by kkafar** [comment]
I already released  4.8.0 with patch

**Comment by hirbod** [comment]
Confirmed, it works!
