### ISSUE TITLE
autoFocus inputs with native stack causes double navigation glitch

### ISSUE THREAD

**Issue by owinter86** [software-mansion/react-native-screens#236]
This is a cross post issue from react navigation ex, as I believe it is caused by react native screens.

### Current Behavior

- Navigating to a screen using createNativeStackNavigator will cause screen to have a double navigation glitch, the animation will reset when the keyboard is activated.
- I can confirm this does not happen with the JS stack navigator.

<img src="https://user-images.githubusercontent.com/2920419/68596338-56beac80-049b-11ea-9349-531d9f9019df.gif" height="400">

### Expected Behavior

- autofocus inputs should not re-trigger the navigation animation, when showing the keyboard.

### How to reproduce

- Navigate to a route with autoFocus TextInput in a native stack navigator.

### Your Environment
    "@react-navigation/core": "^5.0.0-alpha.20",
    "@react-navigation/native": "^5.0.0-alpha.14",
    "@react-navigation/native-stack": "^5.0.0-alpha.9",
    "react-native": "^0.61.5"
    "react-native-screens": "^2.0.0-alpha.12",

https://github.com/react-navigation/navigation-ex/issues/168

**Comment by Jarred-Sumner** [comment]
I have noticed this as well. My workaround was not to use the `autoFocus` prop but instead, to call `.focus()` on the `TextInput` component on `componentDidMount`.

**Comment by owinter86** [comment]
Yep that’s what I am currently doing, intercept the autofocus prop for iOS and call the focus method on the ref, but need at least a 400ms delay on mount to avoid any weird effect.

**Comment by janicduplessis** [comment]
This required a fix in react-native https://github.com/facebook/react-native/pull/27217/commits/217780671048f412afda33abc1b9ce38783a555a

This should make it in the next release (0.62)

**Comment by owinter86** [comment]
Hey @janicduplessis I have just build the 62 RC which includes this commit and can still replicate this issue.

**Comment by shamilovtim** [comment]
Not sure if related but mine are doing this with two times keyboard open?

![Screen Recording 2019-12-29 at 9 33 53 AM](https://user-images.githubusercontent.com/3495974/71558199-8b240300-2a1e-11ea-9fe4-3cd160f79de2.gif)

**Comment by wong2** [comment]
@owinter86 have you tried the latest 0.62.0-rc.2？

**Comment by janicduplessis** [comment]
Original fix didn't fix the issue completely. A better fix has been merged in master but not yet released https://github.com/facebook/react-native/commit/6adba409e6256fd2dcc27a4272edcedae89927af

**Comment by wong2** [comment]
@janicduplessis thanks, will it be included in 0.62 release?

**Comment by owinter86** [comment]
@janicduplessis I have added this commit to the RC candidate locally and resolves this issue.

**Comment by owinter86** [comment]
@wong2 I have requested this gets cherrypicked for the next 62 release candidate, should be a simple pick as I could do it locally quite easily.

**Comment by kmagiera** [comment]
Going to close this issue as the proper fix is outside of the scope of this library.

In order for auto focus to work as in native iOS app, it is necessary for the field to be marked as focused right when it installs. This needed to be change in RN core as autoFocus used to be a prop that'd just call to `focus` with some delay. With @janicduplessis's change to RN when you push a screen with autoFocus on iOS the keyboard will navigate from the side along with the screen.

The temporary workaround I've been using in a couple diff projects was to not rely on autoFocus but call focus on ref from screen appear callback. This does not result in that neat effect when field is focused already during animation but at least you don't get the push animation glitch.

**Comment by owinter86** [comment]
@kmagiera this is also fixed in the new React native release candidate so can be closed anyway.

**Comment by amorino** [comment]
I'm still having this issue using `react-native-screens@2.16.1` and `react-native@0.63.3`

**Comment by harijoe** [comment]
This should be reopened @kmagiera

**Comment by alexfoxy** [comment]
I am coming across this issue in:
```
    "react-native-screens": "^3.18.1",
    "@react-navigation/bottom-tabs": "^6.3.3",
    "@react-navigation/core": "^6.4.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.1",
    "@react-navigation/stack": "^6.3.2",
```

**Comment by ingvardm** [comment]
Same here, please reopen.

**Comment by bryanltobing** [comment]
```json
"react-native-screens": "^3.13.1",
"react-native": "0.68.2",
```

still happening in this version

**Comment by pkayokay** [comment]
@daniel-covelli thanks for the work-around, the only solution that has worked for me.

**Comment by LukasMod** [comment]
Still here in version 
"react-native-screens": "3.34.0",
"react-native": "0.73.8",
"react-navigation/native-stack": "6.11.0"

I can confirm that [workaround](https://github.com/daniel-covelli) is still working. I tried with requestAnimationFrame and InteractionManager.runAfterInteractions with no success without extra delay. So far this listener is the best option.
