### ISSUE TITLE
`ScreenStack.onDismissed` incorrectly called after a navigating back, causing double-back navigation in old architecture

### ISSUE THREAD

**Issue by levibuzolic** [software-mansion/react-native-screens#2525]
### Description

In a navigator with 2 card modals in the stack, calling `navigation.goBack()` causes a double-pop (navigating back 2 screens, instead of 1). This only occurs on the old architecture, switching to the new architecture has the correct behaviour.

It appears that the second `POP` action is being dispatched from `ScreenStack.onDismissed` here: https://github.com/react-navigation/react-navigation/blob/5da190167882859bb3356a84de42be3ca540ef99/packages/native-stack/src/views/NativeStackView.native.tsx#L538-L546

### Steps to reproduce

1. Press `Open modal`
2. Expect screen `One`
3. Press `Open second modal`
4. Expect screen `Two`
5. Press `Back`
6. Expect screen `One` 🚫 

### Snack or a link to a repository

https://github.com/levibuzolic/model-navigation-repro

[Same code as a Expo Snack](https://snack.expo.dev/@levibuzolic/react-navigation---nested-go_back-action), but *does not* reproduce the issue now that Expo Snack is running the new architecture.

### Screens version

4.2.0

### React Native version

0.76.2

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

# Old Architecture

Demonstrates broken behaviour, two models are removed with a single `goBack()` action.

https://github.com/user-attachments/assets/d090d001-98d7-4392-a2b7-14c1494c60fd

# New Architecture

Shows correct behaviour, only one screen removed.

https://github.com/user-attachments/assets/8c1af769-a05d-48fd-91b3-a7a4e6635b65

**Comment by kkafar** [comment]
Thanks for reporting!

**Comment by blytung** [comment]
Ah have the same problem, didn't know if it was expected or not. Spent like 20h trying to solve it and have some hacky workarounds.

**Comment by williamrobertson13** [comment]
Same ^^^

**Comment by vadim-isakov** [comment]
For a while, I resolved the issue by downgrading react-native-screens to version 3.35.0. Unfortunately, this required downgrading several peer dependency libraries as well.

Make sure to check dependencies using the command:
`npx check-peer-dependencies`

Here’s the list of packages I had to downgrade:
```json
{
    "@react-navigation/bottom-tabs": "6.6.1",
    "@react-navigation/devtools": "6.0.27",
    "@react-navigation/material-top-tabs": "6.6.14",
    "@react-navigation/native": "6.1.18",
    "@react-navigation/native-stack": "6.6.1",
    "@react-navigation/stack": "6.4.1",
    "react-native-screens": "3.35.0"
}

**Comment by santomegonzalo** [comment]
this is really annoying... basically adding the react-navigation logger it is showing a `pop` call after calling `back()`... 

<img width="1179" alt="Screenshot 2024-12-05 at 10 57 09" src="https://github.com/user-attachments/assets/9fcfabd3-17ea-4ec6-a30c-f06c37cb9398">

**Comment by santomegonzalo** [comment]
@kkafar any idea when this issue will get solved? sadly the newArchitecture is not an option for everybody because of the amount of 3rd party libraries that didn't update yet :(

**Comment by WinnieS0728** [comment]
in my case I use `react-navigation` v7.
and I solve this by using `@react-navigation/stack` instead of `@react-navigation/native-stack` in the stack where has modal.
it's find with me, maybe because I don't have complex setting.

any other solution?

**Comment by santomegonzalo** [comment]
thats good to know @WinnieS0728 for me that's not an option because we are using the shared components from react-navigation and thats only works with `native-stack`

**Comment by bitcrumb** [comment]
Can confirm this issue. Seeing the same on our app. This is rather unfortunate, since it is not an uncommon situation.

Any update on this issue would be appreciated :)

**Comment by kkafar** [comment]
^ #2568 should resolve the issue. If any of you have capacity to confirm that it works also for you would be great. I'll release another version tomorrow.

**Comment by Kasendwa** [comment]
> issue

Yes it does fix this issue! Thank you so much!

**Comment by Kasendwa** [comment]
> ^ #2568 should resolve the issue. If any of you have capacity to confirm that it works also for you would be great. I'll release another version tomorrow.

Yes it does fix this issue! Thank you so much

**Comment by kkafar** [comment]
Thanks for confirmation & sorry it took that long

**Comment by bitcrumb** [comment]
@kkafar Much appreciated!

**Comment by santomegonzalo** [comment]
looks like it is working great now... is this going to be part of `4.4.0`? 

Thanks @kkafar for the awesome work!

**Comment by kkafar** [comment]
I've released the fix with 4.4.0-rc.1. I expect to release stable version by the end of the weak

**Comment by MrXyfir** [comment]
Forgive me, maybe I'm doing something really dumb, but no one has the issue anymore, right? This should be fully fixed and live?

I'm on 4.4.0 and still have the issue. I've tried fully clearing out my dependencies, cache, rebuild, and the behavior is definitely still there. I'm quite confused...

Do we need `react-navigation` to fix this issue on their end as well? I see they're using 4.4.0 as well...
