### ISSUE TITLE
[react-native-screens] No member named 'parentShadowView' in 'facebook::react::ShadowViewMutation' (Build Failure)

### ISSUE THREAD

**Issue by shubhanshubb** [software-mansion/react-native-screens#2726]
### Description

I am encountering a build error when trying to compile my React Native project with react-native-screens. The error occurs in the RNSScreenRemovalListener.cpp file inside the react-native-screens module.

### Steps to reproduce

Steps to Reproduce:
Create a new React Native project or use an existing one.

npx @react-native-community/cli init MovieApp
cd MovieApp
Install react-native-screens.

yarn add @react-navigation/native @react-navigation/bottom-tabs
yarn add react-native-screens react-native-safe-area-context react-native-vector-icons react-native-gesture-handler react-native-reanimated

cd ios
pod-install

yarn start
The build fails with the above error.

Open Xcode tried to build the project

### Snack or a link to a repository

shubhanshubb/MovieApp

### Screens version

4.8.0

### React Native version

0.78.0

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

Iphone 16

### Acknowledgements

Yes

**Comment by kkafar** [comment]
4.8.0 does not support RN 0.78. Only version that supports it right now is 4.9.0-beta.0.

**Comment by shubhanshubb** [comment]
@kkafar so which version react native satble now so I don't get any error as in RN 0.77 also same issue is there

**Comment by kkafar** [comment]
when running on RN 0.77 you **can't** get this error, because `parentShadowView` member was removed from mutation types in RN 0.78

**Comment by shubhanshubb** [comment]
Yes, you are correct with RN 0.77 , It's working fine

**Comment by kkafar** [comment]
Would you ming opening `RNSDefines.h` and taking a look at what definition of `MUTATION_PARENT_TAG` macro is chosen?

**Comment by irmakcosarsahna** [comment]
same problem rn v0.78

**Comment by kkafar** [comment]
@irmakcosarsahna could you provide me with information I've asked for above?

**Comment by irmakcosarsahna** [comment]
@kkafar  I solved the problem using [4.9.0-beta.0](https://www.npmjs.com/package/react-native-screens/v/4.9.0-beta.0), but I downgraded react native version because many packages do not support version 78 :(

**Comment by kkafar** [comment]
This is not really a solution. 

In case anyone still encounters the problem please provide me with your dependency list (I'm interested in `react-native-screens` & `react-native`) + the information I ask for [here](https://github.com/software-mansion/react-native-screens/issues/2726#issuecomment-2676431444).

Alternatively (that would be the best option) please provide a reproduction.

At the moment I consider the problem solved.

**Comment by trickyc0d3r** [comment]
NO, problem still persist

**Comment by joshwinter** [comment]
I can also confirm the issue still exists in 4.9.0.

**Comment by kkafar** [comment]
I've just released 4.9.1 that should solve the problem. Let me know whether it works for you!

**Comment by Irfanwani** [comment]
> I've just released 4.9.1 that should solve the problem. Let me know whether it works for you!

Thank you for so quick response. Yes it fixed the issue but i am facing other issue. As Appdelegate.mm and main.m files were removed in RN 0.78.0, i am still getting an error that these files are missing. Why?

**Comment by kkafar** [comment]
@Irfanwani, these files are not shipped with the library, but rather directly owned by you as application developer. Most likely you haven't properly removed them (XCode still keeps track of them in the cache).

**Comment by Irfanwani** [comment]
@kkafar do you mean, i need to clear xcode cache or anything else.

**Comment by Irfanwani** [comment]
Is there an automated way to update project.pbxproj. It is hard to update manually.

**Comment by kkafar** [comment]
Reinstalling pods should do the trick I believe - `pod install` / `bundle exec pod install` in `ios/` directory.

**Comment by Irfanwani** [comment]
No it doesn't update all the things. 
seems we need to manually do it

**Comment by Irfanwani** [comment]
I think i got it, remove the reference from xcode, add files there (Appdelegate.swift) and run pod install.

**Comment by Irfanwani** [comment]
What about upgrading from objective c++ to swift. Is it necessary and how to do it incase we don't have any idea of the languages?

**Comment by expertzappdev** [comment]
@kkafar hey getting error ,     "react-native-screens": "^4.13.1", and     "react-native": "0.76.5",


<img width="1296" height="406" alt="Image" src="https://github.com/user-attachments/assets/798b3b5d-6b52-44ca-8742-f10b6e69b70d" />

**Comment by AliHassan5927** [comment]
@kkafar Got the same issue. I've already tried different approaches `like pod deintegrate`, `pod cache clean`, `Delete Pods folder`, `Delete Podfile.lock` Here are my package versions:

```
react-native: 0.76.9
react-native-reanimated: ^3.18.0
react-native-screens: ^4.10.0
```


<img width="1257" height="616" alt="Image" src="https://github.com/user-attachments/assets/6cd35a8b-0c9b-4051-8eef-386dbe3a1735" />

**Comment by trygodson** [comment]
Please I am having this issue, Been stuck for days. It seems it's an upgrade somewhere..... Please How can i fix

https://github.com/software-mansion/react-native-screens/issues/2726#issuecomment-3135879824

**Comment by AliHassan5927** [comment]
I've resolved this by disabling New Architecture from Podfile:

#Disable New Architecture for compatibility
`ENV['RCT_NEW_ARCH_ENABLED'] = '0'`

**Comment by trygodson** [comment]
> I've resolved this by disabling New Architecture from Podfile:
> 
> #Disable New Architecture for compatibility `ENV['RCT_NEW_ARCH_ENABLED'] = '0'`

I have react native reanimated as a package too, which works with New Architecture.. Is there a way out of this

**Comment by AliHassan5927** [comment]
i also have `react-native-reanimated: 3.18.0` and it's working well

**Comment by AdrishS-AW** [comment]
my solution: https://github.com/software-mansion/react-native-screens/issues/2594#issuecomment-3150125036
