### ISSUE TITLE
[native-stack] fullScreenModal and stackAnimation: flip hangs app

### ISSUE THREAD

**Issue by ivopatty** [software-mansion/react-native-screens#374]
**Current Behavior**

I have the following navigation structure
- Main native stack navigator
   - Welcome Screen (this is the initial route)
   - Sign In Screen
   - Sign Up Screen

So I've set up SignUp Screen to navigate with the options `options={{headerShown: false, stackPresentation: "fullScreenModal", stackAnimation: 'flip'}}`

**Succesful paths:** 
Welcome Screen -> Sign In Screen -> Sign Up Screen
Here I can move between screens no problem and sign in normally

**Steps to reproduce**
Navigate from Welcome Screen -> Sign Up Screen 
Any buttons or navigation actions hang or ar not executed 

This similary applies to actions executed that change the navigation tree. So when removing all screens in the stack to replace them with the authenticated screens

software | version
-- | --
iOS or Android | iOS 13
@react-navigation/native | 5.0.7
@react-navigation/native-stack | 5.0.5
react-native-screens | 2.0.0-beta.10
react-native |  0.61.4
expo | 36
node | v12.14.1
npm or yarn  | yarn 1.21.1

**Comment by WoLewicki** [comment]
It looks like the same issue as #436. It should be resolved with #438. I am closing it. If it is not the same issue, feel free to comment to reopen.

**Comment by ivopatty** [comment]
@WoLewicki In my testing #438 has not resolved the issue. Please find a reproducible example for my problem here:  https://github.com/ivopatty/modal-flip-reproduce-example

This affects my simulator on  13.4 and 12.4 as well as my iPhone Xr @ 13.3.1

Thank you!

**Comment by WoLewicki** [comment]
It looks like I made a mistake by adding the check in the wrong method. Try #441 and please tell if it fixes your issue.

**Comment by ivopatty** [comment]
That does indeed fix the issue! Thank you so much :)
