### ISSUE TITLE
Keyboard doesn't show up when use someRef.current.focus()

### ISSUE THREAD

**Issue by AndriiBoiko** [software-mansion/react-native-screens#472]
Hey!
When use
```
someRef.current.focus()
```
nothing happends
but if use
```
setTimeout(() => someRef.current.focus(), 0)
```
I don't think that this a good idea
It is a bug?

```
{
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.9",
    "@react-navigation/native": "^5.1.5",
    "@react-navigation/stack": "^5.2.10",
    "@types/react-navigation": "^3.4.0",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-screens": "^2.4.0",
  },
}

```

**Comment by WoLewicki** [comment]
Can you create a snack that will show the issue? And what Platform does the bug occur on?

**Comment by AndriiBoiko** [comment]
Hey!

> Can you create a snack that will show the issue?

A little bit later, sorry, very busy

> And what Platform does the bug occur on?
Android...

**Comment by Hirbod** [comment]
This is true, when you try to focus on component mount. It also does not work for me without timeout. But for me .current.focus doesn't work anyway, I need to run it like this:

`input.current?._root?.focus?.();`

**Comment by janicduplessis** [comment]
This should be fixed in react-native 0.63 (currently in RC). See https://github.com/facebook/react-native/commit/6adba409e6256fd2dcc27a4272edcedae89927af, https://github.com/facebook/react-native/commit/055a41b081c5bc9535b071d9b4b7488b92e71803,

**Comment by ammichael** [comment]
So RN 0.63 is finally here and the problem persists. Any solution that doesn't require to work it around with timeouts?

**Comment by WoLewicki** [comment]
Did you check on RN 0.63.2?

**Comment by ammichael** [comment]
@WoLewicki yes, that's exactly the one we're using

**Comment by WoLewicki** [comment]
cc @janicduplessis

**Comment by WoLewicki** [comment]
@ammichael can you be more specific on what exactly does not work and could you provide a repo with an easy reproduction of the issue?

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.

**Comment by reyanshmishra** [comment]
I have this did anyone of you solve it?

**Comment by joaocosta9** [comment]
was anyone able to solve this problem? It was working on react native 0.59, but I upgraded to 0.63 and is not working anymore

**Comment by WoLewicki** [comment]
@reyanshmishra @joaocosta9 can you provide a reproduction of this issue in [TestExample](https://github.com/software-mansion/react-native-screens/tree/master/TestsExample) project?

**Comment by KatiRasanen** [comment]
Also noticing the same issue with RN 0.64.1. 

The above hack `setTimeout(() => someRef.current.focus(), 0)` seems to work.

**Comment by cristianoccazinsp** [comment]
Noticed this on RN 0.65.1 as well. Can we re-open? It did not happen with RN 0.62.2 though. So RN broke something here...

**Comment by WoLewicki** [comment]
Please provide a minimal reproduction of the issue and then we can reopen it.

**Comment by cristianoccazinsp** [comment]
After some digging, I don't really think this is related to this library at all.  

RN 0.65 (or 0.64?) changed something in the native dispatching order that ends up delaying certain changes.  For example, changing a prop and immediately running `ref.someMethod` (on the setState callback), on Android, will result in the prop not being ready / updated yet, requiring an extra `setTimeout` call. The same cannot be reproduced on iOS.

For the input focus issue, the behaviour is similar.  Do a state change that renders the input (e.g., conditionally rendering it), and immediately call `ref.focus()`.  This will result in the focus not firing because the input is technically not ready on the setState callback, which causes the issue (and can be fixed with a timeout).

I've tried with `enableScreens(false);` and the issue persists, so it's not a problem with this library, but rather RN.

**Comment by JoshBot-Debug** [comment]
Even I'm facing the same issue on android. Adding a delay makes it work

**Comment by j3sch** [comment]
Same here

**Comment by KevinBarrera** [comment]
Hi everyone, I was able to get this working using `blur()` before `focus()`
```

  useEffect(() => {
    setTimeout(() => {
      inputRef.current?.blur();
      inputRef.current?.focus();
    }, 100);
  }, []);
```
I got it from here: https://github.com/react-native-modal/react-native-modal/issues/516#issuecomment-997961846

**Comment by JoshBot-Debug** [comment]
Here's a snack demonstrating the issue. [https://snack.expo.dev/ScBliGjOX]
I left comments. Most forms in my app are wrapped in a modal. Sometimes I need auto focus.

**Comment by UkioMaeni** [comment]
const interval=setInterval(() =>{
          if(!Keyboard.isVisible()){

              inputRef.current.blur()
              inputRef.current.focus()
          }else {

              clearInterval(interval)
          }

       }, 50)

**Comment by sivercone** [comment]
I have made it work without setTimeout, but it doesn't work in all cases

```javascript
import { Keyboard } from 'react-native';

if (Platform.OS === 'android') Keyboard.dismiss();
textInputRef.current?.focus();
```

**Comment by Mrudula-Nemani** [comment]
I'm encountering the same issue, that despite successfully focusing on the text input when the user presses the edit button, the keyboard fails to open automatically.
