### ISSUE TITLE
Modals don't close on iOS when navigating to a screen with presentation 'push'

### ISSUE THREAD

**Issue by nimabrownlee** [software-mansion/react-native-screens#721]
## Description

When navigating to `TestScreen` from another screen that has a `formSheet` presentation the form sheet/modal does not close upon navigation. Is this expected behaviour? And how can I fix it?

## Code

```js
              <RootStack.Navigator
                screenOptions={{
                  stackPresentation: 'formSheet',
                }}
              >
                <RootStack.Screen
                  name="Test"
                  component={TestScreen}
                  options={{
                    stackPresentation: 'push',
                  }}
                />
              </RootStack.Navigator>
```

### Package versions

- React: 16.13.1
- React Native: 0.63.3
- React Native Screens: 2.10.1+

**Comment by WoLewicki** [comment]
On the iOS native side, modal screens are higher in the view hierarchy than the normal ones. As long as you don't dismiss the modal or add another modal on top of it, the normal views will not be visible above it. You can use `navigation.replace()` in the modal screen to pop the modal and then navigate to the desired screen. Does it resolve your issue?

**Comment by nimabrownlee** [comment]
@WoLewicki Hey, thanks. It works but somehow Typescript complains. I am using the `useNavigation` hook. Should I add a type somewhere?

**Comment by WoLewicki** [comment]
`replace` action was not present in the TS types due to a mistake, it has been fixed in a PR: https://github.com/software-mansion/react-native-screens/pull/695, which is available from v. `2.15.0`. Can you check if upgrading the version or just adding this change to your files resolves the issue?

**Comment by nimabrownlee** [comment]
@WoLewicki Unfortunately it doesn't fix the issue after upgrading.

`TS2339: Property 'replace' does not exist on type 'NavigationProp  , string, Readonly{ key: string; index: number; routeNames: string[]; history?: unknown[] | undefined; routes: (Readonly{ key: string; name: string; params?: object | undefined; }> & { ...; })[]; type: string; stale: false; }>, {}, {}>'.`

**Comment by WoLewicki** [comment]
Can you provide a repo/snack with minimal configuration needed to reproduce the issue? Then I can see for myself what is the problem exactly.

**Comment by nimabrownlee** [comment]
@WoLewicki Also expo complains that `2.15.0` is incompatible with other packages and that I should downgrade. I will post a repo in the following days when I can find time in the work schedule. Thanks for the help.

**Comment by WoLewicki** [comment]
Oh, if you are using Expo, you should stay with the version that is provided by Expo, otherwise, you can have problems with the integration of the JS and native side. It is better just to apply this one commit since it only changes types.
