### ISSUE TITLE
Header background color doesn't work (IOS only)

### ISSUE THREAD

**Issue by teachdugsimt** [software-mansion/react-native-screens#844]
## Description

1. I used Nesting navigators like this 
root stack nav -> stack nav -> bottom tab -> stack nav (last stack screen)
2. Header style (backgroundColor) in my header in last stack screen doesn't work
3. Have some screen work but some screen don't work. 
4. when close app and reopen app then sometime it work fine (yellow header) but sometime it doesn't work(transparent header).

### Screenshots
<img width="421" alt="Screen Shot 2564-03-05 at 15 59 43" src="https://user-images.githubusercontent.com/65938999/110092759-869a6d80-7dcc-11eb-9af4-7357f1ae57b6.png">

<img width="420" alt="Screen Shot 2564-03-05 at 16 09 23" src="https://user-images.githubusercontent.com/65938999/110093355-34a61780-7dcd-11eb-9da0-53c93bad4a25.png">

## Steps To Reproduce
```
import { createNativeStackNavigator } from "react-native-screens/native-stack"
const Stack = createNativeStackNavigator<PrimaryMoreParamList>()
const HeaderCenter = (props: any) => {
  const { tx, text, ...rest } = props
  const textProps = tx ? { tx } : { text }
  return (<Text {...textProps} {...rest} preset="topic" />)
}
export function MoreNavigator() {
  return (
    <Stack.Navigator
      screenOptions={{
        headerShown: true,
        gestureEnabled: true,
        headerStyle: {
          backgroundColor: 'yellow',  // It should be yellow color
        },
        stackAnimation: 'slide_from_right',
      }}
    >
      <Stack.Screen name="more" component={MoreScreen}
        options={({ navigation, route }) => ({
          headerCenter: () => <HeaderCenter tx={"moreScreen.moreMenu"} />,
          headerHideShadow: false,
        })}
      />
    </Stack.Navigator>
  )
}
```

- "react-native-screens": "^2.17.1",
- "@react-navigation/bottom-tabs": "^5.11.2",
- "@react-navigation/native": "^5.1.5",
-  "@react-navigation/stack": "^5.14.2",

**Comment by msvargas** [comment]
I have the same issue, this working fine in the previous version 2.17.1.

**Comment by Preeternal** [comment]
I can't to set headerHideShadow into true with version > 2.17.1.

**Comment by teachdugsimt** [comment]
> @WoLewicki I have the same issue but with (2.18.x), this working fine in the previous version 2.17.1.

I'm still this issue with 2.18.1

**Comment by teachdugsimt** [comment]
> I can't to set headerHideShadow into true with version > 2.17.1.

I can set headerHideShadow in 2.18.1

**Comment by hehex9** [comment]
Same issue (headerStyle & headerHideShadow) here but appears randomly, pretty hard to reproduce it consistently

**Comment by teachdugsimt** [comment]
note 1 : It ever work normally, but after i clean project and npm install - yarn install then this problem occur
note 2 : I try to dowgrade react-native-screens to 2.10.x - 2.18.x but It doesn't work same

**Comment by WoLewicki** [comment]
Can you check if #847 fixes the bug?

**Comment by hehex9** [comment]
Unfortunately the bug still exists

**Comment by WoLewicki** [comment]
Can you provide a code example with minimal configuration needed to reproduce the issue then?

**Comment by teachdugsimt** [comment]
Wait a moment 

> Can you check if #847 fixes the bug?

This can fix. Thank you @WoLewicki

**Comment by WoLewicki** [comment]
I will close this when we confirm that the bug is resolved. No problem @teachdugsimt.

**Comment by hehex9** [comment]
This problem is more likely to occur on the simulator, the following code is hard to reproduce on the real device.

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/9209882/110509150-c18a0180-813c-11eb-8995-e71b37d51928.mov

</details>

<details>
<summary>repro code</summary>

```js
require('react-native-screens').enableScreens()

import React from 'react'
import {Text, View, Button, StyleSheet} from 'react-native'
import {NavigationContainer} from '@react-navigation/native'
import {createNativeStackNavigator} from 'react-native-screens/native-stack'

const defaultOptions = {
  headerHideShadow: true,
  headerTintColor: 'red',
  headerStyle: {backgroundColor: '#f0f0f0'},
  contentStyle: {backgroundColor: '#f0f0f0'},
}

function Main({navigation}) {
  const times = React.useRef(8)
  const id = React.useRef(0)

  React.useEffect(() => {
    id.current = setInterval(() => {
      if (times.current) {
        navigation.navigate('modal-stack')
        setTimeout(() => navigation.goBack(), 500)
        times.current--
      } else {
        clearInterval(id.current)
      }
    }, 1500)
    return () => clearInterval(id.current)
  }, [navigation])

  return (
    <View style={styles.container}>
      <Button
        title='modal'
        onPress={() => navigation.navigate('modal-stack')}
      />
    </View>
  )
}

function Modal({navigation}) {
  return (
    <View style={styles.container}>
      <Button title='back' onPress={() => navigation.goBack()} />
    </View>
  )
}

const ModalStack = createNativeStackNavigator()
function ModalNavigator() {
  return (
    <ModalStack.Navigator
      screenOptions={{...defaultOptions, headerTitle: 'modal'}}
    >
      <ModalStack.Screen
        name='modal'
        component={Modal}
        options={{headerLeft: () => <Text>cancel</Text>}}
      />
    </ModalStack.Navigator>
  )
}

const Stack = createNativeStackNavigator()
export default function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator screenOptions={defaultOptions}>
        <Stack.Screen
          name='main'
          component={Main}
          options={{headerShown: false}}
        />
        <Stack.Screen
          name='modal-stack'
          component={ModalNavigator}
          options={{
            headerShown: false,
            stackPresentation: 'containedModal',
          }}
        />
      </Stack.Navigator>
    </NavigationContainer>
  )
}

const styles = StyleSheet.create({
  container: {flex: 1, justifyContent: 'center', alignItems: 'center'},
})
```

</details>

and I noticed that if the `headerLeft` in ModalStack is not provided, it seems that everything will work fine then. Hope this helps

**Comment by teachdugsimt** [comment]
[navigation.zip](https://github.com/software-mansion/react-native-screens/files/6113361/navigation.zip)
here my navigation ?

**Comment by kacperkapusciak** [comment]
Hi @hehex9,
Thank you very much for this great repro! 🚀 
I've double-checked it and changes made by @WoLewicki in [this file](https://github.com/software-mansion/react-native-screens/pull/847/files#diff-c27cca0a72136c4b43dbfb6319e61fef4204856916d56fc600d28ee798719291) will resolve your issue when the PR will be merged.
 
 <details>
<summary>video</summary>
<br>

https://user-images.githubusercontent.com/39658211/110602372-3b92a880-8186-11eb-960b-e645305908f5.mov

</details>

**Comment by hehex9** [comment]
After a clean build on simulator with the patch, I think the bug should be fixed now (at least we haven't had the same problem yet), now sure why it didn't work yesterday 🤔️

Anyway, thanks for your help ❤️

**Comment by cschultz1272** [comment]
I'm still having this issue even after a clean build with 2.18.1

**Comment by owinter86** [comment]
@cschultz1272 its merged in the master branch and hasn't been released yet, you will need to use parch-package to include it in your build until the next release.

**Comment by cschultz1272** [comment]
@owinter86 I tried putting the code in manually and rebuilding but that still doesn't work.

**Comment by fdecampredon** [comment]
Sorry to bother you, but do you know when we can expect a release with this fix ?

**Comment by WoLewicki** [comment]
We don't have a specific date unfortunately. We try to make the releases when there are a couple new meaningful commits on master.

**Comment by vinnyjth** [comment]
Appreciate you fixing this. This has been a big issue in our apps, so will be very thankful when the next build is released so we can point back at `npm` instead of the git repo.

**Comment by m-ruhl** [comment]
@WoLewicki I still have the issue with `3.0.0`

**Comment by kacperkapusciak** [comment]
Hi @m-ruhl,
This fix will be included in v3.1.0 that will hopefully come this week. We wanted to keep the scope of v3.0.0 as small as possible. Check [release notes](https://github.com/software-mansion/react-native-screens/releases/tag/3.0.0) for more information.

**Comment by Razorholt** [comment]
Is it safe to install v3.1 with Expo? I'd like to use v3 but it's not currently a possibility with that bug. Thanks!

**Comment by WoLewicki** [comment]
You cannot update native code while using Expo managed workflow. It is compiled inside the application, so the only things that you can change there are the changes made in JS.
