### ISSUE TITLE
Keyboard doesn't show up when autoFocus on component mount

### ISSUE THREAD

**Issue by AlexandreMaistret** [software-mansion/react-native-screens#89]
Hello,

I am trying to use react-native-screens combine with react-navigation for my app for better performance, however I have a weird problem. Indeed, when I have a new page mounting with a `TextInput` set on `autoFocus`, it focused as expected but the keyboard does not show up on the screen.

If I don't put `useScreens()` it works perfectly, the TextInput is focused and the Keyboard appears.

react-native: 0.59.1;
react-navigation: 3.8.1;
react-native-screens: 1.0.0-alpha.22;
OS: Android;
Device: Real;

**Comment by mifi** [comment]
Same problem on all platforms and simulators?
I guess you could workaround it by using a ref to the TextInputand calling .focus() but it should work out of the box with autofocus too.

**Comment by llamaluvr** [comment]
I am seeing this, as well, on Android. If I push a screen onto a React Navigation StackNavigator, and autoFocus is set on a TextInput, the TextInput is focused, but the keyboard does not pop up (or maybe it pops up and is immediately dismissed, hard to tell). If I don't call `useScreens()` on Android, then I have no issue.

react-native-screen: 1.0.0-alpha.22
react-navigation: 3.8.0
Expo: SDK 31
Android: 8.0 / Galaxy S8 (device)

**Comment by AlexandreMaistret** [comment]
@mifi Indeed it is possible to make a work around with `.focus()` and `DidFocus();` with `NavigationEvents`, but the user experience is not the same at all since it takes around 0.5-1s to show the keyboard giving the impression that the app is lagging, whereas with autoFocus, the keyboard pop up straight away.

**Comment by mifi** [comment]
Yea, it seems this project has quite a few issues compared to plain View-based screens that need to resolved. Everything is more complicated in Native code than in JS.

**Comment by ferrannp** [comment]
I see the same on my Pixel 2 (Android 9.0).

**Comment by Palid** [comment]
Bump?

**Comment by ferrannp** [comment]
@Palid any ideas in mind where the problem is and possible fixes?

**Comment by Palid** [comment]
My idea is that because it's creating a new native view it just doesn't propagate focus event properly on Android. Haven't researched it properly yet, though.

**Comment by Luckygirlllll** [comment]
Any updates for this problem? I have this problem in Android. 

I have tried to use autoFocus and ref, but it didn't help. What workarounds did you use? 

 ```
componentDidMount() {
        this.ref.focus();
    }

 <TextInput
                            ref={ref => this.ref = ref}
                            autoFocus={true}
                            value={this.props.reflection}
                            onChange={ e => this.props.onChange('reflection', e) }
                        />  

```

**Comment by acartine** [comment]
> Any updates for this problem? I have this problem in Android.
> 
> I have tried to use autoFocus and ref, but it didn't help. What workarounds did you use?
> 
> ```
> componentDidMount() {
>        this.ref.focus();
>    }
> 
> <TextInput
>                            ref={ref => this.ref = ref}
>                            autoFocus={true}
>                            value={this.props.reflection}
>                            onChange={ e => this.props.onChange('reflection', e) }
>                        />  
> ```

Me too ^^^

any workarounds for this?

**Comment by jslok** [comment]
Same problem here.

I'm using a settimeout in componentdidmount to trigger the focus after some milliseconds, but still not the best because there is a necessary delay. 
`setTimeout(() => this.ref.focus(), 100)`
Remove autoFocus prop on the component or else it won't work.

Looking forward to a better solution if possible.

**Comment by jslok** [comment]
react-navigation NavigationEvents component seems to also work using the onDidFocus prop, but it feels slower than using the setTimout like above.

`<>
        <NavigationEvents onDidFocus={() => this.refs.searchbar.focus()} />
        <Searchbar
          ref="searchbar"
          placeholder="Search"
          onChangeText={this._handleChangeText}
          value={this.state.searchTerms}
        />
      </>`

**Comment by ferrannp** [comment]
Can you try `2.0.0-alpha3`? This https://github.com/kmagiera/react-native-screens/pull/152/files should solve the issue.

**Comment by capJavert** [comment]
@ferrannp I had the same problem and can confirm that `2.0.0-alpha.3` fixes this issue.

**Comment by AlexandreMaistret** [comment]
I confirm that with `2.0.0-alpha3` it works now ! Sorry for answering so late but I had to update all my react-native package to use `2.0.0-alpha3` version.

**Comment by yasir-netlinks** [comment]
@AlexandreMaistret its mentioned in reactnavigation docs to install `react-native-screens@^1.0.0-alpha.23` so I'm not sure what I have to do to upgrade `react-native-screens` and why they are recommending this particular version!

**Comment by mnzaki** [comment]
Can this be backported to 1.0 as well for people who are still RN < 0.60.....

**Comment by capJavert** [comment]
@mnzaki people with RN < 0.60 can probably use something like [patch-package](https://www.npmjs.com/package/patch-package) to manually modify and maintain changes while using older version of library.

**Comment by konjoinfinity** [comment]
> Same problem here.
> 
> I'm using a settimeout in componentdidmount to trigger the focus after some milliseconds, but still not the best because there is a necessary delay.
> `setTimeout(() => this.ref.focus(), 150)`
> Remove autoFocus prop on the component or else it won't work.
> 
> Looking forward to a better solution if possible.

I was able to get this to work using a shortened timer (50ms), thank you to the workaround above.

```
Platform.OS === "ios" ? this.ref.focus() : setTimeout(() => this.ref.focus(), 50)
```

**Comment by mnzaki** [comment]
I would like to avoid using things like `patch-package`, too many moving parts for my taste....
Also it is rather straightforward to backport this fix for now: https://github.com/mnzaki/react-native-screens/tree/fix_1.0_soft_keyboard

This branch works for me, and I am wondering if it is possible to PR it and release a 1.0-alpha.24 version? @kmagiera @ferrannp thoughts?

**Comment by kmagiera** [comment]
2.0-alpha is compatible with 1.0-alpha in terms of react-navigation integration. You should be safe to upgrade to 2.0 where I believe the issue has been fixed

**Comment by mnzaki** [comment]
The problem is with androidx. A lot of projects are still not androidx compatible, and moving to 2.0 forces androidx

**Comment by iamgerardm** [comment]
I personally am still seeing this issue with 2.0.0-alpha.17 && react-navigation: 4.0.10 on Android devices.

**Comment by abegehr** [comment]
having this issue on react-native-screens ^2.0.0-alpha.27

**Comment by kmagiera** [comment]
mind preparing a minimal app that demonstrates how the issue can be reproduced @iamgerardm ?

**Comment by velraj-t2s** [comment]
400ms only working for me

Platform.OS === "ios" ? this.ref.focus() : setTimeout(() => this.ref.focus(), 400)

**Comment by Pierre-CLIND** [comment]
Still not working on :
"react-native-screens": "^2.7.0",
   "react-navigation": "^4.3.8",

**Comment by gitKempf** [comment]
Had the same issue.
setTimeout and react-native-screens upgrading didn't help.

**Solved it** by removing autoFocus={true}.
I have a popup as a functional component and using "current.focus()" with Refs like this:
```
const Popup = ({
  placeholder,
  autoFocus,
  showStatus,
}) => {
  const inputRef = useRef(null);
  useEffect(() => {
    if (autoFocus) {
      inputRef.current.focus()
    }
  }, [showStatus]);
  return (
    <View style={styles.inputContainer}>
      <TextInput
        style={styles.inputText}
        defaultValue={placeholder}
        // autoFocus={autoFocus}
        ref={inputRef}
      />
    </View> 
};
```

**Comment by acro5piano** [comment]
I solved the problem by showing `TextInput` only in focused screen. In other words, re-show `TextInput` fire auto focus.

```jsx
  const [isFocused, setIsFocued] = React.useState(true)

  const setFocus = React.useCallback(() => {
    setIsFocued(true)
  }, [])

  const setBlur = React.useCallback(() => {
    setIsFocued(false)
  }, [])

  return (
    <View>
        {focused && <TextInput autoFocus />}
    </View>
  )
```

**Comment by goodryanboy** [comment]
`const _input = useRef();

  useEffect(() => {
    setTimeout(() => {
      _input.current.input.focus();
    }, 400);
  });

    
<Input
        ref={_input}
        placeholder="Say something about this..."
        inputStyle={style.inputShareStyle}
        inputContainerStyle={{borderBottomWidth: 0}}
        placeholderTextColor="#90949c"
      />`

make sure in android you removed autofocus

**Comment by SamuelPinho** [comment]
For anyone looking for some typescript implementation

```tsx
const MyTextInput = ({ autoFocus, ...props }: TextInputProps) => {
  const ref = useRef<TextInput>(null);

  useEffect(() => {
    autoFocus &&
      setTimeout(() => {
        if (ref.current) {
          ref.current.focus();
        }
      }, 40);
  });

  return <TextInput ref={ref} {...props} />;
};
```

**Comment by clind-arthur** [comment]
Here it's working with InteractionManager:

useEffect(() => {
    if (autoFocus && inputRef.current) {
      if (inputRef.current) {
        InteractionManager.runAfterInteractions(() => {
          inputRef.current?.focus();
        });
      }
    }
  }, [autoFocus, editable, inputRef]);

**Comment by kanakdesai** [comment]
> Hello,
> 
> I am trying to use react-native-screens combine with react-navigation for my app for better performance, however I have a weird problem. Indeed, when I have a new page mounting with a `TextInput` set on `autoFocus`, it focused as expected but the keyboard does not show up on the screen.
> 
> If I don't put `useScreens()` it works perfectly, the TextInput is focused and the Keyboard appears.
> 
> react-native: 0.59.1;
> react-navigation: 3.8.1;
> react-native-screens: 1.0.0-alpha.22;
> OS: Android;
> Device: Real;

if you are using Visual Studio, go to I/O -> keyboard-> toggle software keyboard. The keyboard should appear. And for it to disappear use this :
import {Keyboard} from 'react-native'

`import {Keyboard} from 'react-native'

<TouchableWithoutFeedback onPress={Keyboard.dismiss} accessible={false}>
    <View style={{flex: 1}}>
        <TextInput keyboardType='numeric'/>
    </View>
</TouchableWithoutFeedback>`

**Comment by Momics** [comment]
For anyone stumbling on this issue. Here is a reusable TS hook using clind-arthur's example:

```ts
import React from "react";
import { InteractionManager, TextInput } from "react-native";

export default function useAutoFocus(autoFocus = true) {
  const inputRef = React.useRef<TextInput>(null);

  React.useEffect(() => {
    if (autoFocus && inputRef.current) {
      if (inputRef.current) {
        InteractionManager.runAfterInteractions(() => {
          inputRef.current?.focus();
        });
      }
    }
  }, [autoFocus, inputRef]);

  return inputRef;
}
```

**Comment by radoncreep** [comment]
Hi everyone, for me this issue isn't from react native as "autoFocus" prop works perfectly.

I had a simliar issue just moments ago, then applied some solutions here but it couldn't fix my issue.

In my case, I wanted to rendered a searchbar on the "homescreen" and I had three components being rendered to achieve this

The first component is where my navigation functionality resides
`<Stack.Screen
                name="slicedonion" 
                component={AppNavigator}
                options={{ 
                    headerShown: true,
                    headerStyle: { backgroundColor: '#0f011f'}, 
                    headerTitleStyle: { color: '#fff' },
                    headerRight: () => (
                        <AppSearch />
                    )
                }} 
                />
`
as you can see, I rendered a component "AppSearch" (Second component) at the right side of my stack screen header

In this component I had two sub-functional components 
i) renderIcon() - renders a search icon
ii) renderSearchModal - renders a modal containing a custom search-bar which has "TextInput" with the "autoFocus" prop and flatlist to render searched items (you get the idea)

I made a mistake of rendering both sub-components conditionally in the same component (AppSearch), which initially renders the icon but when clicked renders the modal.

This is a mistake because when "AppSearch" renders, both sub-components also render, so does the lifecycle of each subs
According to the docs, "autoPlay" prop focuses when "componentDidMount" fires, so when the homescreen renders, so does "AppSearch", which also renders the Modal component in it, which is not in use until I click the icon. This makes the componentDidMount of  my "renderSearchModal" execute before use or before it showing up, for some reason it just does in the background.

I guess I am making this confusing, but since the modal component has rendered when it wasn't in use , and the icon gets clicked.... the modal fades in with the "TextInput in it, and the keyboard doesn't automatically open because autoFocus has already been executed by the initial componentDidMmount.

What I had to do is to separate my components as an Icon on it's own and modal on its own, but share state as props between them. This way the modal doesn't get rendered until it is opened and when it is open, componenDidMount for the modal component executes triggering autoFocus and automating the appearance of the keyboard.

Though I have a question on why "autoFocus" uses componentDidMount to function.

Also, I am a react toddler, if I made a mistake please correct me.

**Comment by raybotha** [comment]
> For anyone stumbling on this issue. Here is a reusable TS hook using clind-arthur's example:
> 
> ```ts
> import React from "react";
> import { InteractionManager, TextInput } from "react-native";
> 
> export default function useAutoFocus(autoFocus = true) {
>   const inputRef = React.useRef<TextInput>(null);
> 
>   React.useEffect(() => {
>     if (autoFocus && inputRef.current) {
>       if (inputRef.current) {
>         InteractionManager.runAfterInteractions(() => {
>           inputRef.current?.focus();
>         });
>       }
>     }
>   }, [autoFocus, inputRef]);
> 
>   return inputRef;
> }
> ```

This works.
Why is this issue closed? It's definitely a significant bug that's still around.

**Comment by Abdul-1Basit** [comment]
This issue doesn't seems to be getting resolved. :D
Here are both examples, showing the keyboard and also closing on tapping anywhere on screen, if anyone needs it.

import React, { useEffect, useRef } from "react";
import {
  Dimensions,
  StyleSheet,
  Text,
  View,
  Image,
  TouchableOpacity,
  Keyboard,
} from "react-native";

import { DrawerContentScrollView, DrawerItem } from "@react-navigation/drawer";

import { Foundation } from "@expo/vector-icons";
import {
  TextInput,
  TouchableWithoutFeedback,
} from "react-native-gesture-handler";

import imgg from "../../assets/Images/corr.png";

const screenWidth = Dimensions.get("window").width;
const screenHeight = Dimensions.get("window").height;

const PinCode = (props) => {
  const DismissKeyboard = ({ children }) => {
    <TouchableWithoutFeedback
      onPress={() => {
        Keyboard.dismiss();
      }}
    >
      {children}
    </TouchableWithoutFeedback>;
  };
  const [keyCode, setKeyCode] = React.useState("");
  const _input = useRef(null);
  useEffect(() => {
    setTimeout(() => {
      _input.current.focus();
    }, 400);
  });
  return (
    <View style={{ flex: 1, backgroundColor: "#FFF" }}>
      <View
        style={{
          width: screenWidth,
          height: screenHeight / 2.3,
          backgroundColor: "#FFF",
          alignItems: "center",
          justifyContent: "center",
          flexDirection: "column",
        }}
      >
        <Image
          source={imgg}
          resizeMode={"contain"}
          style={{ width: 150, height: 150, alignContent: "center" }}
        />
        <Text
          style={{ fontWeight: "bold", letterSpacing: 3, color: "#ff0000" }}
        >
          OCMB MOBILE BANKING
        </Text>
      </View>
      <View
        style={{
          width: screenWidth,
          height: "100%",
          backgroundColor: "#ff0000",
          paddingTop: 20,
        }}
      >
        <View
          style={{
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <View style={{ marginHorizontal: 10 }}>
            <Foundation name="key" size={27} color="#FFF" />
          </View>
          <View>
            <Text
              style={{
                textAlign: "center",
                fontSize: 17,

                letterSpacing: 2,
                color: "#FFF",
              }}
            >
              Enter Passcode
            </Text>
          </View>
        </View>
        <View style={{ alignItems: "center", justifyContent: "center" }}>
          <TextInput
            keyboardType="number-pad"
           
            secureTextEntry={true}
            value={keyCode}
            ref={_input}
            onChangeText={(text) => {
              console.log(text);
           setKeyCode(keyCode)
            }}
            style={{
              color: "#FFF",
              letterSpacing: 10,
              marginTop: 10,
              fontSize: 20,
            }}
          />
        </View>
      </View>
    </View>
  );
};
export default PinCode;

**Comment by 10000multiplier** [comment]
anybody have an idea about how to ```autoFocus``` the 'react-native-screens' searchbar?

**Comment by Titozzz** [comment]
Here is a repro to this still ongoing issue: https://github.com/Titozzz/android-autofocus-issue

**Comment by Titozzz** [comment]
cc @WoLewicki

**Comment by Coreeze** [comment]
> Had the same issue. react-native-screens upgrading didn't help.
> 
> **Solved it** by removing autoFocus={true} and setting timeout. I have a popup as a functional component and using "current.focus()" with Refs like this:
> 
> ```
> const Popup = ({
>   placeholder,
>   autoFocus,
>   showStatus,
> }) => {
>   const inputRef = useRef(null);
>   useEffect(() => {
>      Platform.OS === 'ios'
>         ? inputRef.current.focus()
>         : setTimeout(() => inputRef.current.focus(), 40);
>   }, [showStatus]);
>   return (
>     <View style={styles.inputContainer}>
>       <TextInput
>         style={styles.inputText}
>         defaultValue={placeholder}
>         ref={inputRef}
>       />
>     </View> 
> };
> ```

Also had this problem. I used this and also documentation from here: https://reactnavigation.org/docs/function-after-focusing-screen/

**Comment by WoLewicki** [comment]
Can you check if https://github.com/software-mansion/react-native-screens/pull/1214 fixes the issue so you don't need any timeouts or such in order for the `autofocus` to work and if it does not introduce any new issues?

**Comment by WoLewicki** [comment]
Closing since it should be fixed by #1214.

**Comment by j3sch** [comment]
Whether my component will be displayed depends on the state. After the state updates to true, and my Input gets displayed it shows the cursor but not the keyboard.

**Comment by taylorkline** [comment]
Can confirm that this issue is fixed for me by upgrading to React Native Screens 3.17.0, thanks @WoLewicki

**Comment by chaudhariyatin** [comment]
> I solved the problem by showing `TextInput` only in focused screen. In other words, re-showing `TextInput` fires auto focus again.
> 
> ```js
> const useNavigationFocus = () => {
>   const [isFocused, setIsFocued] = React.useState(true)
> 
>   const setFocus = React.useCallback(() => {
>     setIsFocued(true)
>   }, [])
> 
>   const setBlur = React.useCallback(() => {
>     setIsFocued(false)
>   }, [])
> 
>   const navi = useNavigation()
> 
>   React.useEffect(() => {
>     navi.addListener('focus', setFocus)
>     navi.addListener('blur', setBlur)
>     return () => {
>       navi.removeListener('focus', setFocus)
>       navi.removeListener('blur', setBlur)
>     }
>   }, [])
> 
>   return { isFocused }
> }
> 
> const MyScreen = () => {
>   const { isFocused } = useNavigationFocus()
>   return (
>     <View>
>         {isFocused && <TextInput autoFocus />}
>     </View>
>   )
> ```

>Instead of checking screen is focused or not we can render search bar after some time interval. this solved my problem
`import {Searchbar} from 'react-native-paper';

const [focus, setFocus] = useState(false);
useEffect(() => {
    focusSearchBar();
  }, []);

  const focusSearchBar = () => {
    setTimeout(() => {
      setFocus(true);
    }, 10);
  };`


return (
<View>
{focus ? (
          <SearchBar  autoFocus={true} />
  ) : null}
</View>
)

**Comment by Archi-G** [comment]
Adding these 2 properties solved my issue - 
```
focusable={true}
autoFocus={true}
```
