### ISSUE TITLE
Flicker when navigating around

### ISSUE THREAD

**Issue by alexandrius** [software-mansion/react-native-screens#905]
## Description
When navigating back, after navigation animation is finished previous screen is shown for a moment. After it disappears. Sometimes it works fine.
See footage below

### Screenshots
https://user-images.githubusercontent.com/5978212/116809884-92e34280-ab51-11eb-94d1-ee7314125ead.mov

https://user-images.githubusercontent.com/5978212/116809890-9971ba00-ab51-11eb-9ec5-a3dd267f5d94.mov

## Steps To Reproduce

1. Navigate to second screen 
2. Go back to previous screen

### Expected behavior
Previous screen shouldn't be shown after navigating back

### Actual behavior
Previous screen is shown for very short moment after navigating back

## Package versions

- React: 16.13.1
- React Native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz
- React Native Screens: 3.0.0
- React Navigation: 4.4.4
- React Navigation Stack: 2.10.4
- React Navigation Tabs: 2.11.1
- Expo: 41.0.0

**Comment by Razorholt** [comment]
Same issue here but not as obvious. For me it happens from the drawer.

**Comment by kacperkapusciak** [comment]
Could you provide a minimal reproducible example of your issue?

**Comment by alexandrius** [comment]
> Could you provide a minimal reproducible example of your issue?

I will try later today

**Comment by alexandrius** [comment]
It seems it's harder to reproduce on blank project.
At the end of the video previous page flickers for a moment
https://user-images.githubusercontent.com/5978212/117048331-e907df80-ad23-11eb-8f2e-02a32251d85f.mp4

Here's the repo
https://github.com/alexandrius/screens-flicker

**Comment by obernal** [comment]
Just in case it's helpful. We don't use Expo and have the exact same issue:

* React Native: 0.64
* React Native Screens: 3.2.0 (also tried on 2.x with same issue)
* React Navigation: 4.4.4
* React Navigation Stack: 2.10.4
* React Navigation Tabs: 2.11.1

Disabling `react-native-screens` stops the flicker.

**Comment by superyarik** [comment]
@obernal disabling = remove from package.json?

**Comment by obernal** [comment]
> @obernal disabling = remove from package.json?

 `enableScreens(false)` seems to be enough.

**Comment by Razorholt** [comment]
I don't know how disabling react-native-screens fixes the issue.

**Comment by obernal** [comment]
> I don't know how disabling react-native-screens fixes the issue.

My comment is not meant to be used as a fix but as additional information that the flicker only happens when it's enabled. Or do you mean you see the flicker even after disabling it?

**Comment by Razorholt** [comment]
@obernal Thanks for the clarifications. Well yes, the flicker disappears when I disable react-native-screens. Does the latest release of screens fixes the issue? I haven't tried it since my project is using expo.

**Comment by alexandrius** [comment]
> @obernal Thanks for the clarifications. Well yes, the flicker disappears when I disable react-native-screens. Does the latest release of screens fixes the issue? I haven't tried it since my project is using expo.

enableScreens(false) fixes the flicker for me as well

**Comment by RyanTG** [comment]
This issue persists for me on 3.0.0, 3.2.0, and 2.18.1. I'm using react navigation 4.4.4. I don't know the ins and outs of these things, but it kinda makes it seem like it's a react nav 4.4.4 issue...

**Comment by RyanTG** [comment]
@alexandrius I made a snack from your repo, just in case that helps the debugging process.

**Comment by lc3t35** [comment]
I have the same kind of flickering when navigating between screen (expo sdk41 - managed)

```
"react-native": "0.63.4",
"@react-navigation/compat": "^5.3.15",
"@react-navigation/core": "^5.15.3",
"@react-navigation/native": "^5.9.4",
"@react-navigation/stack": "^5.14.4",
"react-native-screens": "~3.0.0",
```

screenshot is here : https://github.com/react-navigation/react-navigation/issues/9557

**Comment by joebernard** [comment]
Rolling back to `react-native-screens@2.15.2` seems to fix the issue. The problem first occurs in 2.17.0.

My packages:
```
"react-native": "0.64.1",
"react-native-screens": "3.3.0",
"react-navigation": "4.4.4",
"react-navigation-props-mapper": "1.0.4",
"react-navigation-stack": "2.10.4",
"react-navigation-tabs": "2.11.1",
```

**Comment by RyanTG** [comment]
Rolling screens back to 2.15.2 seems to have solved the flicker issue for me.

Thanks! You're more intrepid than I. I previously only downgraded to 2.18 when trying other versions! argh

**Comment by alexandrius** [comment]
@joebernard I think you are describing different kind of flicker. Also I don't think that's react-native-screens related

**Comment by joebernard** [comment]
I was seeing the exact flicker you described at the top of this issue. Navigating back would quickly flash the popped screen. Rolling back screens solved it for me and someone else. Please try rolling back and let us know if it helped.

**Comment by flow-danny** [comment]
Also solved it for me, thanks!

**Comment by lc3t35** [comment]
This solution cannot work with "@react-navigation/core": "^5.15.3", as it embed "react-native-screens": ~3.00 ...

**Comment by lc3t35** [comment]
Here is a snack with react-navigation version 5 : https://snack.expo.io/@shares/screens-flicker-v5

**Comment by superyarik** [comment]
@lc3t35 sorry, how did you get 14.4.2 on iPhone 5S?

**Comment by lc3t35** [comment]
> @lc3t35 sorry, how did you get 14.4.2 on iPhone 5S?

my bad "SE" -> fixed comment

**Comment by eclecticjohny** [comment]
Can confirm rolling back to 2.15.2 fixes issue in our project that is same as issue described by OP.

**Comment by WoLewicki** [comment]
@lc3t35 did you spot the flickering behavior in v5 navigators? I believe the flicker comes from changes from this PR: https://github.com/software-mansion/react-native-screens/pull/777/files, but I don't know why it seems to only happen in v4 navigation for me, and why does it even happen. The issue is that when the asynchronous update at the end of going back animation, which detaches the former screen, is triggered, the screen we navigated from is rendered on top of the view hierarchy for one frame, causing the flicker to be visible from time to time. It does not happen for in v5 stack. The workaround is to revert the changes from the PR I linked, but it is not a solution since it is somehow connected to navigation v4, so probably the problems lies somewhere in its code.

**Comment by lc3t35** [comment]
I applied with expo sdk41 / react-navigation v5 , enableScreens(false) with react-native-screens 2.15.2 and changed useSafeAreaInsets which has performance issues as stated by [documentation](https://github.com/th3rdwave/react-native-safe-area-context#consumers) to a standard SafeAreaInsetsContext.Consumer to get the insetsvalue and adapt View's padding accordingly. No more jump / flickering whatever you call this problem.

**Comment by WoLewicki** [comment]
I think your problem was other than the one described in the issue then. Could you elaborate on https://github.com/software-mansion/react-native-screens/issues/905#issuecomment-860647715 @alexandrius @obernal ?

**Comment by obernal** [comment]
> @lc3t35 did you spot the flickering behavior in v5 navigators? I believe the flicker comes from changes from this PR: https://github.com/software-mansion/react-native-screens/pull/777/files, but I don't know why it seems to only happen in v4 navigation for me, and why does it even happen. The issue is that when the asynchronous update at the end of going back animation, which detaches the former screen, is triggered, the screen we navigated from is rendered on top of the view hierarchy for one frame, causing the flicker to be visible from time to time. It does not happen for me in v5 stack. The workaround is to revert the changes from the PR I linked, but it is not a solution since it is somehow connected to navigation v4, so probably the problems lies somewhere in its code.

@WoLewicki this makes a lot of sense but I haven't tried in v5 so I can't confirm. Should be relatively easy to try @alexandrius repo with v5 though. If I get some time today I'll give that a try. I'll also take a look at https://github.com/software-mansion/react-native-screens/pull/777/files 
Thanks for the additional information. Hopefully we are getting closer to finding a permanent solution to this 👍

**Comment by WoLewicki** [comment]
Can you check if applying #986 fixes the problem?

**Comment by alexandrius** [comment]
> Can you check if applying #986 fixes the problem?
I am gonna test it on the weekend

**Comment by charles-goode** [comment]
Tried rolling back to 2.15.2, but it didn't solve the problem ( I'm on Expo 41 managed FYI). I am using react-navigation v4, react-navigation-stack@2.10.3. This only occurs on iOS for my app.

**Comment by obernal** [comment]
@WoLewicki I just applied the changes from #986 and can confirm that I don't see the flicker anymore with `react-native-screens` enabled 🎉. Thanks for finding a solution to this! Probably worth having others here try it as well but it looks good from my side 👍

**Comment by Razorholt** [comment]
How to fix that problem when using Expo and RN 5?

**Comment by WoLewicki** [comment]
@charles-goode @Razorholt the fix involves native code, so it is not possible to add it to Expo managed workflow. Hopefully, we will include this change in Expo SDK 42, which is going to be out soon.

**Comment by Razorholt** [comment]
For those of you using Expo, I'm currently testing SDK 42 (with screens v3.4.0) and so far it seems that the issue has been fixed. Thanks a lot guys!

**Comment by rumfiske** [comment]
Any news regarding this? I hvae same problem, running expo SDK 49

**Comment by Dat-Mobile** [comment]
I can still see the issue with bare React native project, without Expo. With new architecture enabled

```
"react-native": "0.76.5",
"react-native-screens": "^4.4.0",
"@react-navigation/bottom-tabs": "^7.2.0",
"@react-navigation/material-top-tabs": "^7.1.0",
"@react-navigation/native": "^7.0.14",
"@react-navigation/stack": "^7.1.1",
```

**Comment by DorinHavardi** [comment]
> I can still see the issue with bare React native project, without Expo. With new architecture enabled
> 
> ```
> "react-native": "0.76.5",
> "react-native-screens": "^4.4.0",
> "@react-navigation/bottom-tabs": "^7.2.0",
> "@react-navigation/material-top-tabs": "^7.1.0",
> "@react-navigation/native": "^7.0.14",
> "@react-navigation/stack": "^7.1.1",
> ```

same for me

import {enableScreens} from 'react-native-screens';

enableScreens(false);

on index.js solve it though
